### ISSUE TITLE
Please update it in PyPI.

### ISSUE THREAD

**Issue by bjjdkp** [richardpenman/browsercookie#13]
https://github.com/richardpenman/browsercookie/pull/10#issue-1115740391
Please update it in PyPI.
Thanks!

**Comment by watercrossing** [comment]
Likewise, an update on PyPI would be appreciated.

**Comment by oldium** [comment]
@richardpenman Could you update PyPI with latest version, please?

**Comment by richardpenman** [comment]
Sure, uploaded to pypi
