### ISSUE TITLE
Add support for the Brave Browser

### ISSUE THREAD

**Issue by carlitorendon** [richardpenman/browsercookie#21]
Great project. Looking forward to have support for the Brave Browser

**Comment by richardpenman** [comment]
Great, I look forward to your PR!

**Comment by carlitorendon** [comment]
Working on it. Hope to submit soon

**Comment by carlitorendon** [comment]
Sent #22 @richardpenman, again thank you for this library!

**Comment by richardpenman** [comment]
Awesome, thanks for the PR!

**Comment by carlitorendon** [comment]
No worries, thank you for this awesome library
